name: Package

on:
  - push

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - &setup-uv
        name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: '0.5.x'
          cache-dependency-glob: "uv.lock"
          python-version: '3.12'
      - name: install dev dependencies
        run: uv sync --all-extras --dev
        &install-dev
      - name: Run ruff
        run: ruff format --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *setup-uv
      - *install-dev
      - name: Run ruff
        run: ruff check

  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *setup-uv
      - *install-dev
      - name: Run mypy
        run: mypy .

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10", "3.9"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: '0.5.x'
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}
      - *install-dev
      - name: Run pytest
        run: pytest

  build_source_dist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *setup-uv
      - name: install all dept
        run: uv sync
      - name: Run build
        run: python -m build --sdist
      - uses: actions/upload-artifact@v4
        name: build and upload artifact
        with:
          path: ./dist/*.tar.gz

  publish:
    name: Publish package
    if: startsWith(github.event.ref, 'refs/tags/')
    needs:
      - format
      - lint
      - typecheck
      - test
      - build_source_dist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
